import os
import datetime
import json
try:
    from jinja2 import Template
    JINJA_AVAILABLE = True
except ImportError:
    JINJA_AVAILABLE = False
except Exception:
    JINJA_AVAILABLE = False

class ReportGenerator:
    """Generates professional HTML reports for bug bounty results."""
    
    HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AIbot-bug Beast Mode Report</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: #e2e8f0; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: auto; background: #1e293b; padding: 40px; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 1); }
        h1 { color: #38bdf8; border-bottom: 2px solid #38bdf8; padding-bottom: 10px; }
        .stat-card { background: #334155; padding: 20px; border-radius: 8px; margin: 10px 0; display: inline-block; min-width: 150px; text-align: center; }
        .severity-high { border-left: 5px solid #ef4444; }
        .severity-med { border-left: 5px solid #f59e0b; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #475569; }
        th { background-color: #334155; color: #38bdf8; }
        .footer { margin-top: 40px; font-size: 0.8em; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <h1>AIbot-bug Scan Report</h1>
        <p><strong>Generated on:</strong> {{ timestamp }}</p>
        
        <div class="summary">
            <div class="stat-card"><h3>Subdomains</h3><p>{{ results.subdomains|length }}</p></div>
            <div class="stat-card"><h3>Vulns Found</h3><p>{{ results.vulnerabilities|length }}</p></div>
            <div class="stat-card"><h3>Secrets</h3><p>{{ results.secrets|length }}</p></div>
        </div>

        <h2>Validated Findings</h2>
        <table>
            <tr><th>Description</th></tr>
            {% for finding in results.validated_findings %}
            <tr><td>{{ finding }}</td></tr>
            {% endfor %}
        </table>

        <h2>Subdomains Discovered</h2>
        <ul>
            {% for sub in results.subdomains[:50] %}
            <li>{{ sub }}</li>
            {% endfor %}
        </ul>

        <h2>Vulnerabilities Matrix</h2>
        <table>
            <tr><th>Type/Info</th></tr>
            {% for vuln in results.vulnerabilities %}
            <tr><td class="severity-high">{{ vuln }}</td></tr>
            {% endfor %}
        </table>

        <div class="footer">
            Generated by AIbot-bug 4.0 - Beast Mode Enabled
        </div>
    </div>
</body>
</html>
"""

    @staticmethod
    def generate_html(results, target_name):
        """Creates a professional HTML report from the results dictionary."""
        if not JINJA_AVAILABLE:
            print("Error: Jinja2 not installed or broken. Falling back to simple JSON report.")
            filename = f"report_{target_name}.json"
            with open(filename, "w") as f: json.dump(results, f, indent=4)
            return filename
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        template = Template(ReportGenerator.HTML_TEMPLATE)
        html_content = template.render(results=results, timestamp=timestamp)
        
        filename = f"report_{target_name.replace('://', '_').replace('.', '_')}.html"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        return filename
